# 📘 NumPy Basics for Machine Learning


**NumPy** stands for **Numerical Python** and is used for numerical computations, especially in machine learning and data science.
It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions.


In [1]:
import numpy as np

## 🛠️ Array Creation

In [16]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [3, 4, 5]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [3 4 5]]


## 🔍 Array Properties

In [17]:

print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)


Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int32


## 🧱 Special Arrays

In [ ]:

print(np.zeros((2, 2)))
print(np.ones((3, 2)))
print(np.eye(3))
print(np.arange(0, 20, 5))
print(np.linspace(0, 5, 5))  # division by equal parts


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  5 10 15]
[0.   1.25 2.5  3.75 5.  ]


## ➕ Arithmetic Operations

In [5]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)


Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]


## 🔄 Reshape and Flatten

In [31]:

arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print("Reshape to 3x2:\n", arr.reshape(2, 6))
print("Flatten to 1D:", arr.flatten())


Reshape to 3x2:
 [[ 1  2  3  4  4  5]
 [ 6  7  7  8  9 10]]
Flatten to 1D: [ 1  2  3  4  4  5  6  7  7  8  9 10]


## 🎯 Indexing and Slicing

In [36]:

arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[1])
print("Last two elements:", arr[-2:])

# Array Index starts from 0
matrix = np.array([[1, 2], [3, 4]])
print("Element at row 1, col 1:", matrix[0, 0])
 
# 1 2 [a[0, 0] a[0, 1]]
# 3 4 [a[1, 0], a[1, 1]]

First element: 20
Last two elements: [40 50]
Element at row 1, col 1: 1


## 📊 Statistical Functions

In [38]:

data = np.array([10, 20, 30, 40])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))


Sum: 100
Mean: 25.0
Median: 25.0
Standard Deviation: 11.180339887498949


## 🎲 Random Number Generation

In [ ]:

print("Random 1D:", np.random.rand(10))
print("Random integers:", np.random.randint(1000000, 9999999, 3))
# Doubt
np.random.seed(42)


Random 1D: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
Random integers: [5523669 8404852 5981505]


## 🧮 Matrix Operations

In [10]:

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix multiplication:\n", np.dot(a, b))
print("Transpose:\n", a.T)
print("Inverse:\n", np.linalg.inv(a))


Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
